# Setup
title: Ka Yoon Kim
description: Making the better society with technology
url: https://gayoooon1.github.io
avatar: https://avatars.githubusercontent.com/u/60475072?v=4 #/avatar.jpeg
paginate: 5
permalink: pretty
cover_image: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQITZ7oWn9aJkxIEQ7XFgrrT7KW9jmKfXKo3vvT1diyjxb9SGcWEPEp4ARDEX2xSNfK4Ts&usqp=CAU  #/bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
#twitter:
  #username: NULL
  #card: NULL
logo: logo.png
social:
  name: Ka Yoon Kim
  links:
    #- https://twitter.com/vszhub
    - https://github.com/gayoooon1
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Ka Yoon Kim
  url: https://github.com/gayoooon1
  email: shiaky3821@gmail.com
