# Setup
title: Blog
description: Wreck it!
url: https://gayoooon1.github.io
avatar: https://gamek.mediacdn.vn/zoom/345_230/2018/11/27/image011-15432928693671837985857-crop-1543293223112373061751.jpg #https://avatars.githubusercontent.com/u/60475072?v=4 #/avatar.jpeg
paginate: 5
permalink: pretty
cover_image: http://images6.fanpop.com/image/photos/38600000/Wreck-It-Ralph-Concept-Art-Poster-wreck-it-ralph-38610898-768-1152.png #https://simplytodaylife.com/wp-content/uploads/2015/10/ZTA_CROSSWALK_SIGN_1s_v14.0r_Composed_Mechv8_5MB.jpg  #/bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
#twitter:
  #username: NULL
  #card: NULL
logo: logo.png
social:
  name: Ka Yoon Kim
  links:
    #- https://twitter.com/vszhub
    - https://github.com/gayoooon1
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Ka Yoon Kim
  url: https://github.com/gayoooon1
  email: shiaky3821@gmail.com
